apiVersion: v1
kind: ConfigMap
metadata:
  name: semaphore-config
  namespace: default
data:
  application.properties: |
    # Add your Spring Boot configuration here
    server.port=8080
    management.endpoints.web.exposure.include=health,metrics,prometheus
    management.endpoint.health.show-details=always